export const PETFOOD_LIST_REQUEST = 'PETFOOD_LIST_REQUEST';
export const PETFOOD_LIST_SUCCESS = 'PETFOOD_LIST_SUCCESS';
export const PETFOOD_LIST_FAIL = 'PETFOOD_LIST_FAIL';

export const PETFOOD_DETAIL_REQUEST = 'PETFOOD_DETAIL_REQUEST';
export const PETFOOD_DETAIL_SUCCESS = 'PETFOOD_DETAIL_SUCCESS';
export const PETFOOD_DETAIL_FAIL = 'PETFOOD_DETAIL_FAIL';
